Update sendToSteph.yml

diff --git a/.github/workflows/sendToSteph.yml b/.github/workflows/sendToSteph.yml
--- a/.github/workflows/sendToSteph.yml
+++ b/.github/workflows/sendToSteph.yml
@@ -33,7 +33,7 @@ jobs:
         echo TryMerge
         # git merge --no-commit upstream/toPrivateRickAndSteph 2>&1
         # and recording the output for in a moment
-        merge_result=$(git merge --no-commit upstream/toPrivateRickAndSteph 2>&1) # Use upstream/toPrivateRickAndSteph
+        merge_result=$(git merge -m "Merged from icarus5.5 on $(date)" upstream/toPrivateRickAndSteph 2>&1) # Use upstream/toPrivateRickAndSteph
         echo $merge_result
         echo Results...
         if [[ "$merge_result" =~ "Automatic merge failed" || "$merge_result" =~ "CONFLICT" ]]; then
@@ -49,8 +49,8 @@ jobs:
           
         else
           echo "No conflicts detected during sim. Actually merging..."
-          git merge upstream/toPrivateRickAndSteph || { echo "Error: Merge failed."; exit 1; }
-          git commit -m "Merged from icarus5.5 on $(date)" || { echo "Error: Commit failed."; exit 1; }
+          # git merge upstream/toPrivateRickAndSteph || { echo "Error: Merge failed."; exit 1; }
+          # git commit -m "Merged from icarus5.5 on $(date)" || { echo "Error: Commit failed."; exit 1; }
           git push forky main || { echo "Error: Push failed."; exit 1; } # Push to your repo
       
           echo "Performing action for no conflicts..."
